### ISSUE TITLE
Expose cpus_per_task

### ISSUE THREAD

**Issue by msalganik** [niznik-dev/cruijff_kit#449]
## For Mattie

**Problem.** PyTorch's DataLoader has a `num_workers` argument that controls how many subprocess workers prepare batches in parallel. With the default `num_workers=0`, all data prep (tokenization + chat-template formatting + collation) happens single-threaded in the main training process, blocking the GPU. The slurm scripts also default to `--cpus-per-task=1`. cruijff_kit's torchtune templates don't expose either knob, so every fine-tune we run today is effectively single-threaded data loading on a single core, even when more capacity is available.

**Why fix it.** The `consistency_curve_pilot_nth14_k20` N=1000 finetune ran at 97% CPU efficiency on a single core, while the GPU sat at 70% utilization (verifiably waiting on the CPU). Bumping just the slurm allocation does nothing if `num_workers` is unset — the workers default to 0 and the extra cores sit idle. With both knobs configurable, we expect GPU utilization to climb to 90%+ and training-only wallclock to drop ~20–25% across all our consistency-curve experiments.

**What changes after the fix.**
- `controls.cpus_per_task: 8` in `experiment_summary.yaml` reaches the generated `finetune.slurm` (`#SBATCH --cpus-per-task=8`).
- `controls.num_workers: 4` reaches both `dataset:` and `dataset_val:` blocks of the generated `finetune.yaml`.
- `controls.persistent_workers: true` does the same (saves worker-startup cost across our 3-epoch runs).
- Existing experiments that don't set these fields are unaffected: `cpus_per_task` falls back to 1 (current behavior), `num_workers` falls back to 0 (PyTorch default), `persistent_workers` falls back to false.

**Acceptance.**
1. Setting all three fields in `controls` of `experiment_summary.yaml` causes them to appear in the generated `finetune.slurm` and `finetune.yaml` for every fine-tuned run.
2. With these set, `seff <jobid>` reports `Cores: 8` and total CPU time scaled across cores; GPU utilization in `gpu_metrics.csv` reaches 90%+ during training periods.
3. Three regression tests cover the propagation path (one per knob).

**Effort estimate.** ~25 lines source across 3 files + ~30 lines tests.

---

### Investigation already done

Don't re-investigate — go straight to the patch.

- `src/tools/torchtune/templates/finetune_template.yaml` — has `dataset:` (~line 68) and `dataset_val:` (~line 84) blocks. Neither has `num_workers` or `persistent_workers`.
- The slurm template (find via `find src/tools/torchtune -name '*.slurm*'`) hardcodes `--cpus-per-task=1` and does not read from `setup_finetune.yaml`.
- `src/tools/torchtune/setup_finetune.py` — needs `--num_workers`, `--persistent_workers`, and `--cpus_per_task` CLI flags. Existing flag pattern uses argparse; place near the other dataset-related / slurm-related flags.
- `.claude/agents/scaffold-torchtune.md` — line 230 lists per-run parameter overrides. Add all three to that list and to the controls table.
- The custom recipe (`src/tools/torchtune/custom_recipes/lora_finetune_single_device_nightly.py`) constructs the dataloader from cfg — no recipe changes needed; PyTorch's DataLoader honors the YAML field directly when scaffold-torchtune writes it through.
- Concrete observation: `seff 7604383` (the pilot N=1000 run) shows CPU 36:24 of 37:25 wallclock = 97.3% efficiency on a single core, while `gpu_metrics.csv` averages 70% GPU utilization. Textbook CPU-bound symptom.

### Files to change

Source (3 files):
1. `src/tools/torchtune/templates/finetune_template.yaml` — add `num_workers` and `persistent_workers` fields to both `dataset:` and `dataset_val:` blocks.
2. `src/tools/torchtune/templates/<slurm template>.slurm` — replace hardcoded `--cpus-per-task=1` with templated value defaulting to 1.
3. `src/tools/torchtune/setup_finetune.py` — add three CLI flags (`--num_workers`, `--persistent_workers`, `--cpus_per_task`) and the corresponding template substitutions.

Docs (1 file):
4. `.claude/agents/scaffold-torchtune.md` — document all three under controls and per-run parameters.

Tests (1 file):
5. `tests/unit/test_setup_finetune_main.py` — add regression tests for the propagation path of each knob.

### Patch 1: `finetune_template.yaml`

Inside the `dataset:` block, add:
```yaml
  num_workers: {{ num_workers | default(0) }}
  persistent_workers: {{ persistent_workers | default(false) | lower }}
```
Mirror the same two lines in the `dataset_val:` block. The `|lower` filter is important — Python booleans render as `True`/`False`, but YAML wants `true`/`false`.

### Patch 2: slurm template

Find the line `#SBATCH --cpus-per-task=1` and replace with:
```
#SBATCH --cpus-per-task={{ cpus_per_task | default(1) }}
```

### Patch 3: `setup_finetune.py`

Add CLI flags near the dataset/slurm-related args:
```python
parser.add_argument("--num_workers", type=int, default=None,
                    help="DataLoader num_workers for both train and val "
                         "(default: 0, single-process data loading).")
parser.add_argument("--persistent_workers", type=str, default=None,
                    help="If 'true', keep DataLoader workers alive across "
                         "epochs. Saves spawn cost; ignored when num_workers=0.")
parser.add_argument("--cpus_per_task", type=int, default=None,
                    help="Cores requested in the generated SLURM script "
                         "(default: 1).")
```

In the args→YAML loop, add handling that writes `num_workers` and `persistent_workers` into both dataset blocks, and `cpus_per_task` into the slurm-context dict.

### Patch 4: `scaffold-torchtune.md`

Append to the per-run parameters list (line 230):
```
num_workers: {from run.parameters.num_workers, if present}
persistent_workers: {from run.parameters.persistent_workers, if present}
cpus_per_task: {from run.parameters.cpus_per_task, if present}
```

And add to the controls table around line 88-93:
```
- `controls.num_workers` - DataLoader worker subprocesses (default 0)
- `controls.persistent_workers` - Keep workers alive across epochs (default false)
- `controls.cpus_per_task` - Cores requested in the slurm script (default 1)
```

### Patch 5: `tests/unit/test_setup_finetune_main.py`

Append a new test class:
```python
class TestParallelism:
    def test_num_workers_writes_to_both_dataset_blocks(self, run_main):
        config, _ = run_main(extra_args=["--num_workers", "4"])
        assert config["dataset"]["num_workers"] == 4
        assert config["dataset_val"]["num_workers"] == 4

    def test_persistent_workers_writes_to_both_dataset_blocks(self, run_main):
        config, _ = run_main(extra_args=["--persistent_workers", "true"])
        assert config["dataset"]["persistent_workers"] in (True, "true")
        assert config["dataset_val"]["persistent_workers"] in (True, "true")

    def test_no_num_workers_means_no_field(self, run_main):
        config, _ = run_main()
        assert "num_workers" not in config["dataset"]
        assert "num_workers" not in config["dataset_val"]

    def test_cpus_per_task_writes_to_slurm(self, run_main):
        _, slurm = run_main(extra_args=["--cpus_per_task", "8"])
        assert "--cpus-per-task=8" in slurm

    def test_no_cpus_per_task_defaults_to_one(self, run_main):
        _, slurm = run_main()
        assert "--cpus-per-task=1" in slurm
```

### Test plan

Run from repo root with `cruijff` conda env active.

**a. Unit tests:**
```bash
pytest tests/unit/test_setup_finetune_main.py -v
```

**b. Integration check:**
```bash
mkdir -p /tmp/parallelism_test && cd /tmp/parallelism_test
cp /scratch/gpfs/MSALGANIK/mjs3/ck-experiments/consistency_curve_pilot_nth14_k20/Llama-3.2-3B-Instruct_N1000/setup_finetune.yaml .
# add num_workers: 4, persistent_workers: true, cpus_per_task: 8
python /home/mjs3/cruijff_kit/src/tools/torchtune/setup_finetune.py --config_file setup_finetune.yaml
grep -A4 "^dataset:" finetune.yaml          # expect: num_workers: 4 + persistent_workers: true
grep -A4 "^dataset_val:" finetune.yaml      # same
grep "cpus-per-task" finetune.slurm         # expect: --cpus-per-task=8
```

**c. End-to-end (after the next experiment runs):**
```bash
seff <jobid>  # expect Cores: 8, CPU efficiency well below 100% per core
```

**d. Lint:**
```bash
ruff check src/tools/torchtune/setup_finetune.py tests/unit/test_setup_finetune_main.py
ruff format --check src/tools/torchtune/setup_finetune.py tests/unit/test_setup_finetune_main.py
```

### PR conventions

- Branch: `<issue-number>-cpu-dataloader-parallelism`.
- PR body starts with `Closes #<issue-number>`.

### Out of scope

- Exposing `prefetch_factor` (PyTorch default 2 is fine for our short-batch case; can be added later).
- Exposing tokenizer parallelism (`HF_TOKENIZERS_PARALLELISM` env var).
- Reformatting other parts of the templates.
- The separate `batch_size_val` propagation issue is independent and should land separately.

— Claude x Matt

**Comment by msalganik** [comment]
## Empirical bug-report on the patch as described

I tried to land an out-of-band `post_scaffold_fixup.py` that mirrors this issue's placement (writing `num_workers` and `persistent_workers` into the `dataset:` and `dataset_val:` blocks of `finetune.yaml`). All 7 fine-tunes in `consistency_curve_nth14_k20` failed within 14–80s with:

```
TypeError: chat_completion_dataset() got an unexpected keyword argument 'num_workers'
```

The "no recipe changes needed" claim turns out to be wrong on two counts:

### 1. `chat_completion_dataset()` rejects extras

`src/tools/torchtune/datasets/chat_completion.py:113` defines:

```python
def chat_completion_dataset(
    tokenizer,
    *,
    source: str,
    data_files: str,
    model_path: str,
    ...
):
```

Keyword-only args with no `**kwargs` — any extra key inside the `dataset:` block (which is what Patch 1 adds) is forwarded by `config.instantiate(cfg_dataset, ...)` and raises `TypeError`. So Patch 1 as written doesn't just fail to take effect — it actively breaks every fine-tune.

### 2. Even if the kwarg landed somewhere benign, the recipe never reads it

All three recipes hardcode the `StatefulDataLoader(...)` call with no `num_workers` / `persistent_workers` argument:

- \`src/tools/torchtune/custom_recipes/lora_finetune_single_device_nightly.py:642\`
- \`src/tools/torchtune/custom_recipes/lora_finetune_single_device_stable.py:604\`
- \`src/tools/torchtune/custom_recipes/lora_finetune_distributed_stable.py:665\`

So even with Patch 1 writing the field somewhere that doesn't crash, PyTorch never picks it up — the recipe doesn't pass it through. Acceptance criterion #2 (\"GPU utilization 90%+\") cannot be hit until the recipe also reads these.

### Suggested scope adjustment

Add a Patch 0 (recipe changes) and pick a placement that avoids the strict-kwargs trap. Two clean options:

- **Top-level** (matches the existing \`batch_size_val\` precedent at line 391 of the nightly recipe): scaffold writes \`num_workers:\` and \`persistent_workers:\` at the YAML top level. Each recipe reads via \`cfg.get(\"num_workers\", 0)\` and \`cfg.get(\"persistent_workers\", False)\` and passes them to \`StatefulDataLoader\`. Cleanest, no churn in the dataset blocks.
- **In-block + pop**: scaffold writes inside the \`dataset:\` block as the issue currently describes. Each recipe \`cfg_dataset.pop(\"num_workers\", None)\` and \`cfg_dataset.pop(\"persistent_workers\", None)\` *before* \`config.instantiate(cfg_dataset, ...)\`, then passes them to \`StatefulDataLoader\`. Matches this issue's placement but adds two pops × 2 dataset blocks × 3 recipes = 12 small lines.

Either way, the test plan needs an actual end-to-end check (kick off a small fine-tune, not just a scaffold dry-run) — the proposed unit tests only check file contents, not the runtime path. That's why this didn't get caught until a real submission.

### Empirical evidence

\`\`\`
$ sacct -j 7610608 --format=JobID,JobName,State,Elapsed,ExitCode -X
       JobID                           JobName      State    Elapsed ExitCode
------------ --------------------------------- ---------- ---------- --------
7610608       Llama-3.2-3B-Instruct_N25         FAILED   00:01:19      1:0
\`\`\`

Same failure mode across all 7 sizes (N=25 … N=2000). Recovery was to strip the broken keys from each \`finetune.yaml\` and re-submit. Full incident: \`/scratch/gpfs/MSALGANIK/mjs3/ck-experiments/consistency_curve_nth14_k20/logs/run-experiment.log\`.

**Comment by msalganik** [comment]
Two updates after a closer look during implementation:

## Framing correction

The issue says the slurm template hardcodes `--cpus-per-task=1` and "does not read from `setup_finetune.yaml`." That's not quite right: `setup_finetune.py:937,948-950` already rewrites the template's `=1` placeholder using `MODEL_CONFIGS[model]["slurm"]["cpus"]`. The reason fine-tunes still render with `--cpus-per-task=1` today is that **the MODEL_CONFIGS value is also 1 for almost every entry** — only `Llama-3.3-70B-Instruct` has `cpus: 4`. So the pilot evidence (1 core, 97% efficiency) is right; the mechanism is slightly different from how the issue describes it.

Functionally the fix is the same — add a `--cpus_per_task` CLI/config override that slots in as a third precedence level (CLI > MODEL_CONFIGS > template default 1). I'll cite this framing in the PR rather than repeat the original.

## Scope reduction

After discussion with @msalganik on the wrapper-only design principle ("all fine-tuning code is written and tested by torchtune; cruijff_kit just builds wrappers"), this issue's scope is shrinking to **`cpus_per_task` only** for now.

The `num_workers` and `persistent_workers` knobs both require recipe-level edits (the DataLoader is constructed inside `_setup_data` with no hook, and torchtune is frozen so upstream isn't going to add one). Adding them under the wrapper-only principle would require either:

- patching the three custom recipes (10 patch blocks per recipe already exist there, so there's precedent — but the principle calls for minimizing this), or
- introducing a subclass-based override (a new structural pattern).

Rather than make that call inline on a perf PR, the principle conversation will get its own issue addressed to @niznik-dev. This issue ships the cleanly-wrapper-only piece; the rest is upstream-blocked-and-tracked-separately.

PR coming shortly with `cpus_per_task` only.

**Comment by msalganik** [comment]
Followed up with #465 for the principle-reconciliation discussion. PR #464 ships the wrapper-only piece (`cpus_per_task`); whatever gets decided in #465 will determine whether the rest of #449 (num_workers / persistent_workers) ever ships.

**Comment by msalganik** [comment]
@niznik-dev I played around with this issue a bit, and I wrote a new experiment to test how CPU being close to 100% might decrease GPU utilization which might decrease tokens per second.  The tl;dr is that I have no evidence (yet) that CPU is a bottleneck, but I still think we should all expose cpus_per_task because CPUs are cheap and I've seen CPU bottlenecks in the past.  My AI system will post the results of the next experiment in the next comment. Now are you ready for the big reveal: I designed, ran, and analyzed the experiment all in Codex.  It all worked totally fine, which was very cool.  I think the refactor we did in v0.3 might have helped a lot with cross-platform compatibility.

**Comment by msalganik** [comment]
Very short summary: all five CPU/GPU pipeline-balance runs completed successfully. The short 1B/k16 run is the only case with active GPU utilization below 90%; for longer prompts and larger models, GPU utilization stayed high while CPU efficiency was also saturated, suggesting the CPU was busy but not clearly starving the GPU during active training.

# CPU/GPU Pipeline Balance Report

Generated: 2026-05-08 15:55:34

## Summary

| run | model | k | CPU eff % | active GPU % | active samples >=90% | tokens/sec/gpu | max GPU GB |
|---|---|---:|---:|---:|---:|---:|---:|
| llama32_1b_k16 | Llama-3.2-1B-Instruct | 16 | 74.58 | 83.6 | 87.5 | 132.7 | 4.4 |
| llama32_1b_k128 | Llama-3.2-1B-Instruct | 128 | 86.54 | 93.4 | 100.0 | 105.0 | 8.7 |
| llama32_1b_k512 | Llama-3.2-1B-Instruct | 512 | 97.92 | 95.6 | 66.7 | 28.9 | 23.3 |
| llama32_3b_k512 | Llama-3.2-3B-Instruct | 512 | 98.92 | 97.8 | 91.2 | 9.4 | 41.9 |
| llama31_8b_k512 | Llama-3.1-8B-Instruct | 512 | 98.8 | 96.8 | 86.9 | 8.2 | 72.8 |

## Observed Patterns

- For the 1B prompt-length sweep, active GPU utilization rose from 83.6% at k=16 to 93.4% at k=128 and 95.6% at k=512. CPU efficiency rose from 74.58% to 97.92%, while throughput fell from 132.7 to 28.9 tokens/sec/gpu.
- The short k=16 run is the only run with active GPU utilization below 90%, so it is the clearest case where fixed overheads and input pipeline work are visible relative to GPU compute.
- For the k=512 model-size sweep, active GPU utilization stayed high: 95.6% for 1B, 97.8% for 3B, and 96.8% for 8B. CPU efficiency was also saturated, so the CPU is busy but the GPU does not appear starved during active training.
- Larger models mainly shifted the workload toward GPU compute: wall clock increased from 15.25 minutes for 1B/k512 to 54.25 minutes for 8B/k512, and throughput dropped from 28.9 to 8.2 tokens/sec/gpu.

— Codex & Matt

**Comment by niznik-dev** [comment]
**Scope narrowed 2026-05-11.** Now covers only `cpus_per_task` propagation through the slurm template (Patch 2 + corresponding bits of Patch 3, plus the `cpus_per_task` test in Patch 5). The `num_workers` and `persistent_workers` work described below (Patch 1, parts of Patch 3, those tests in Patch 5) is deferred — file as separate follow-up issues if/when prioritized.

This narrows the lift to a one-knob slurm change so it can land cleanly inside the Overnight Runs Initiative without dragging the full DataLoader-parallelism investigation behind it.

—MxC
